# Generated by Django 3.1.7 on 2021-02-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.CharField(max_length=50)),
                ('per', models.CharField(max_length=50)),
                ('piece', models.CharField(max_length=50)),
                ('sales', models.CharField(max_length=50)),
                ('month', models.CharField(choices=[(1, 'JAN'), (2, 'FEB'), (3, 'MAR'), (4, 'APR'), (5, 'MAY'), (6, 'JUN'), (7, 'JUL'), (8, 'AUG'), (9, 'SEP'), (10, 'OCT'), (11, 'NOV'), (12, 'DEC')], max_length=2)),
                ('year', models.PositiveIntegerField(max_length=4)),
                ('productline', models.CharField(max_length=100)),
                ('dealsize', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large'), ('Medium', 'Medium')], max_length=20)),
            ],
        ),
    ]
